export const CURRENCIES_ES = [
  { code: "USD", name: "Dólar estadounidense" },
  { code: "EUR", name: "Euro" },
  { code: "AED", name: "Dirham de Emiratos Árabes Unidos" },
  { code: "AFN", name: "Afgani afgano" },
  { code: "ALL", name: "Lek albanés" },
  { code: "AMD", name: "Dram armenio" },
  { code: "ANG", name: "Florín de las Antillas Neerlandesas" },
  { code: "AOA", name: "Kwanza angoleño" },
  { code: "ARS", name: "Peso argentino" },
  { code: "AUD", name: "Dólar australiano" },
  { code: "AWG", name: "Florín arubeño" },
  { code: "AZN", name: "Manat azerbaiyano" },
  { code: "BAM", name: "Marco convertible de Bosnia-Herzegovina" },
  { code: "BBD", name: "Dólar de Barbados" },
  { code: "BDT", name: "Taka bangladesí" },
  { code: "BGN", name: "Lev búlgaro" },
  { code: "BHD", name: "Dinar bahreiní" },
  { code: "BIF", name: "Franco burundés" },
  { code: "BMD", name: "Dólar bermudeño" },
  { code: "BND", name: "Dólar de Brunéi" },
  { code: "BOB", name: "Boliviano boliviano" },
  { code: "BRL", name: "Real brasileño" },
  { code: "BSD", name: "Dólar bahameño" },
  { code: "BTN", name: "Ngultrum butanés" },
  { code: "BWP", name: "Pula botsuano" },
  { code: "BYN", name: "Rublo bielorruso" },
  { code: "BZD", name: "Dólar beliceño" },
  { code: "CAD", name: "Dólar canadiense" },
  { code: "CDF", name: "Franco congoleño" },
  { code: "CHF", name: "Franco suizo" },
  { code: "CLP", name: "Peso chileno" },
  { code: "CNY", name: "Yuan chino" },
  { code: "COP", name: "Peso colombiano" },
  { code: "CRC", name: "Colón costarricense" },
  { code: "CUP", name: "Peso cubano" },
  { code: "CVE", name: "Escudo caboverdiano" },
  { code: "CZK", name: "Corona checa" },
  { code: "DJF", name: "Franco yibutiano" },
  { code: "DKK", name: "Corona danesa" },
  { code: "DOP", name: "Peso dominicano" },
  { code: "DZD", name: "Dinar argelino" },
  { code: "EGP", name: "Libra egipcia" },
  { code: "ERN", name: "Nakfa eritreo" },
  { code: "ETB", name: "Birr etíope" },
  { code: "FJD", name: "Dólar fiyiano" },
  { code: "FKP", name: "Libra malvinense" },
  { code: "FOK", name: "Corona feroesa" },
  { code: "GBP", name: "Libra esterlina" },
  { code: "GEL", name: "Lari georgiano" },
  { code: "GGP", name: "Libra de Guernsey" },
  { code: "GHS", name: "Cedi ghanés" },
  { code: "GIP", name: "Libra gibraltareña" },
  { code: "GMD", name: "Dalasi gambiano" },
  { code: "GNF", name: "Franco guineano" },
  { code: "GTQ", name: "Quetzal guatemalteco" },
  { code: "GYD", name: "Dólar guyanés" },
  { code: "HKD", name: "Dólar hongkonés" },
  { code: "HNL", name: "Lempira hondureño" },
  { code: "HRK", name: "Kuna croata" },
  { code: "HTG", name: "Gourde haitiano" },
  { code: "HUF", name: "Forinto húngaro" },
  { code: "IDR", name: "Rupia indonesia" },
  { code: "ILS", name: "Nuevo shéquel israelí" },
  { code: "IMP", name: "Libra de Isla de Man" },
  { code: "INR", name: "Rupia india" },
  { code: "IQD", name: "Dinar iraquí" },
  { code: "IRR", name: "Rial iraní" },
  { code: "ISK", name: "Corona islandesa" },
  { code: "JEP", name: "Libra de Jersey" },
  { code: "JMD", name: "Dólar jamaiquino" },
  { code: "JOD", name: "Dinar jordano" },
  { code: "JPY", name: "Yen japonés" },
  { code: "KES", name: "Chelín keniata" },
  { code: "KGS", name: "Som kirguís" },
  { code: "KHR", name: "Riel camboyano" },
  { code: "KID", name: "Dólar de Kiribati" },
  { code: "KMF", name: "Franco comorense" },
  { code: "KRW", name: "Won surcoreano" },
  { code: "KWD", name: "Dinar kuwaití" },
  { code: "KYD", name: "Dólar de Islas Caimán" },
  { code: "KZT", name: "Tenge kazajo" },
  { code: "LAK", name: "Kip laosiano" },
  { code: "LBP", name: "Libra libanesa" },
  { code: "LKR", name: "Rupia de Sri Lanka" },
  { code: "LRD", name: "Dólar liberiano" },
  { code: "LSL", name: "Loti lesotense" },
  { code: "LYD", name: "Dinar libio" },
  { code: "MAD", name: "Dirham marroquí" },
  { code: "MDL", name: "Leu moldavo" },
  { code: "MGA", name: "Ariary malgache" },
  { code: "MKD", name: "Denar macedonio" },
  { code: "MMK", name: "Kyat birmano" },
  { code: "MNT", name: "Tugrik mongol" },
  { code: "MOP", name: "Pataca macaense" },
  { code: "MRU", name: "Uguiya mauritano" },
  { code: "MUR", name: "Rupia mauriciana" },
  { code: "MVR", name: "Rupia de Maldivas" },
  { code: "MWK", name: "Kwacha malauí" },
  { code: "MXN", name: "Peso mexicano" },
  { code: "MYR", name: "Ringgit malayo" },
  { code: "MZN", name: "Metical mozambiqueño" },
  { code: "NAD", name: "Dólar namibio" },
  { code: "NGN", name: "Naira nigeriana" },
  { code: "NIO", name: "Córdoba nicaragüense" },
  { code: "NOK", name: "Corona noruega" },
  { code: "NPR", name: "Rupia nepalí" },
  { code: "NZD", name: "Dólar neozelandés" },
  { code: "OMR", name: "Rial omaní" },
  { code: "PAB", name: "Balboa panameño" },
  { code: "PEN", name: "Sol peruano" },
  { code: "PGK", name: "Kina de Papúa Nueva Guinea" },
  { code: "PHP", name: "Peso filipino" },
  { code: "PKR", name: "Rupia pakistaní" },
  { code: "PLN", name: "Złoty polaco" },
  { code: "PYG", name: "Guaraní paraguayo" },
  { code: "QAR", name: "Rial catarí" },
  { code: "RON", name: "Leu rumano" },
  { code: "RSD", name: "Dinar serbio" },
  { code: "RUB", name: "Rublo ruso" },
  { code: "RWF", name: "Franco ruandés" },
  { code: "SAR", name: "Riyal saudí" },
  { code: "SBD", name: "Dólar de Islas Salomón" },
  { code: "SCR", name: "Rupia seychelense" },
  { code: "SDG", name: "Libra sudanesa" },
  { code: "SEK", name: "Corona sueca" },
  { code: "SGD", name: "Dólar singapurense" },
  { code: "SHP", name: "Libra de Santa Elena" },
  { code: "SLE", name: "Leona de Sierra Leona" },
  { code: "SOS", name: "Chelín somalí" },
  { code: "SRD", name: "Dólar surinamés" },
  { code: "SSP", name: "Libra sursudanesa" },
  { code: "STN", name: "Dobra de Santo Tomé y Príncipe" },
  { code: "SYP", name: "Libra siria" },
  { code: "SZL", name: "Lilangeni suazi" },
  { code: "THB", name: "Baht tailandés" },
  { code: "TJS", name: "Somoni tayiko" },
  { code: "TMT", name: "Manat turcomano" },
  { code: "TND", name: "Dinar tunecino" },
  { code: "TOP", name: "Pa'anga tongano" },
  { code: "TRY", name: "Lira turca" },
  { code: "TTD", name: "Dólar de Trinidad y Tobago" },
  { code: "TVD", name: "Dólar tuvaluano" },
  { code: "TWD", name: "Nuevo dólar taiwanés" },
  { code: "TZS", name: "Chelín tanzano" },
  { code: "UAH", name: "Grivna ucraniana" },
  { code: "UGX", name: "Chelín ugandés" },
  { code: "UYU", name: "Peso uruguayo" },
  { code: "UZS", name: "Som uzbeko" },
  { code: "VES", name: "Bolívar venezolano" },
  { code: "VND", name: "Dong vietnamita" },
  { code: "VUV", name: "Vatu vanuatense" },
  { code: "WST", name: "Tala samoano" },
  { code: "XAF", name: "Franco CFA de África Central" },
  { code: "XCD", name: "Dólar del Caribe Oriental" },
  { code: "XOF", name: "Franco CFA de África Occidental" },
  { code: "XPF", name: "Franco CFP" },
  { code: "YER", name: "Rial yemení" },
  { code: "ZAR", name: "Rand sudafricano" },
  { code: "ZMW", name: "Kwacha zambiano" },
  { code: "ZWL", name: "Dólar zimbabuense" },
];
